# gems on GitHub Actions
github.com/sue445/activerecord-compatible_legacy_migration:
  tags:
    - github_actions
    - gem

github.com/sue445/activerecord-simple_index_name:
  tags:
    - github_actions
    - gem

github.com/sue445/capistrano-itamae:
  tags:
    - github_actions
    - gem
    - docker

github.com/sue445/chatwork_webhook_verify:
  tags:
    - github_actions
    - gem

github.com/sue445/cure_line:
  tags:
    - github_actions
    - gem

github.com/sue445/date_discreter:
  tags:
    - github_actions
    - gem

github.com/sue445/faker-precure:
  tags:
    - github_actions
    - gem

github.com/sue445/faraday_boolean:
  tags:
    - github_actions
    - gem

github.com/sue445/faraday-mashify:
  tags:
    - github_actions
    - gem

github.com/sue445/fluent-plugin-chatwork:
  tags:
    - github_actions
    - gem

github.com/sue445/gitlab_mr_release:
  tags:
    - github_actions
    - gem

github.com/sue445/google_holiday_calendar:
  tags:
    - github_actions
    - gem

github.com/sue445/index_shotgun:
  tags:
    - github_actions
    - gem
    - db

github.com/sue445/itamae-plugin-recipe-consul:
  tags:
    - github_actions
    - gem
    - itamae_plugin

github.com/sue445/itamae-plugin-recipe-git_now:
  tags:
    - github_actions
    - gem
    - itamae_plugin

github.com/sue445/itamae-plugin-recipe-gitlab_runner:
  tags:
    - github_actions
    - gem
    - itamae_plugin

github.com/sue445/itamae-plugin-recipe-tig:
  tags:
    - github_actions
    - gem
    - itamae_plugin

github.com/sue445/itamae-plugin-resource-encrypted_remote_file:
  tags:
    - github_actions
    - gem
    - itamae_plugin

github.com/sue445/kiriban_getter:
  tags:
    - github_actions
    - gem

github.com/sue445/omniauth-chatwork:
  tags:
    - github_actions
    - gem

github.com/sue445/pixela:
  tags:
    - github_actions
    - gem

github.com/sue445/rspec-temp_dir:
  tags:
    - github_actions
    - gem

github.com/sue445/rspec-time_stop:
  tags:
    - github_actions
    - gem

github.com/sue445/rubicure:
  tags:
    - github_actions
    - gem

github.com/sue445/rubocop-itamae:
  tags:
    - github_actions
    - gem

github.com/sue445/rubocop_auto_corrector:
  tags:
    - github_actions
    - gem

github.com/sue445/sengiri_yaml:
  tags:
    - github_actions
    - gem

github.com/sue445/syobocalite:
  tags:
    - github_actions
    - gem

github.com/sue445/tweet_sanitizer:
  tags:
    - github_actions
    - gem

github.com/sue445/twitter_retry:
  tags:
    - github_actions
    - gem

github.com/sue445/prismdb-ruby:
  tags:
    - github_actions
    - gem

github.com/sue445/faker-pretty_series:
  tags:
    - github_actions
    - gem

github.com/sue445/rubocop-isucon:
  tags:
    - github_actions
    - gem

github.com/sue445/datadog_thread_tracer:
  tags:
    - github_actions
    - gem

github.com/sue445/mysql2-nested_hash_bind:
  tags:
    - github_actions
    - gem

github.com/sue445/doorkeeper_jp:
  tags:
    - github_actions
    - gem

github.com/sue445/itest5ch:
  tags:
    - github_actions
    - gem

github.com/sue445/apple_system_status:
  tags:
    - github_actions
    - gem

github.com/sue445/kagaribi:
  tags:
    - github_actions
    - gem

github.com/sue445/funnel_http:
  tags:
    - github_actions
    - gem

github.com/ruby-go-gem/ruby_header_parser:
  tags:
    - github_actions
    - gem

# Go
github.com/sue445/go-doorkeeper:
  tags:
    - github_actions
    - go

github.com/sue445/gcp-secretmanagerenv:
  tags:
    - github_actions
    - go

github.com/sue445/gcp-kmsenv:
  tags:
    - github_actions
    - go

# dockerfile
github.com/sue445/dockerfile-awscli-all:
  tags:
    - dockerfile

github.com/sue445/dockerfile-heroku-cli:
  tags:
    - dockerfile

github.com/sue445/dockerfile-vagrant-aws:
  tags:
    - dockerfile

# other
github.com/sue445/jenkins-backup-script:
  tags:
    - github_actions
